// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPf9XE_oqIrBF5HO1pDxBZyRrwRVLbM5M',
    appId: '1:318699014160:web:77668bfc01abbb3f91a295',
    messagingSenderId: '318699014160',
    projectId: 'app-flutter-facul',
    authDomain: 'app-flutter-facul.firebaseapp.com',
    storageBucket: 'app-flutter-facul.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDD-6JBuOKzbfs8BYi0dWZsyd0Ao0dARM',
    appId: '1:318699014160:android:1b50e15d06d8651391a295',
    messagingSenderId: '318699014160',
    projectId: 'app-flutter-facul',
    storageBucket: 'app-flutter-facul.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnVh_O9mV0NYaISKJ02T3M1zQvXOgDp7M',
    appId: '1:318699014160:ios:5238ef30ad6c7bd991a295',
    messagingSenderId: '318699014160',
    projectId: 'app-flutter-facul',
    storageBucket: 'app-flutter-facul.firebasestorage.app',
    iosBundleId: 'com.example.trabalhoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnVh_O9mV0NYaISKJ02T3M1zQvXOgDp7M',
    appId: '1:318699014160:ios:5238ef30ad6c7bd991a295',
    messagingSenderId: '318699014160',
    projectId: 'app-flutter-facul',
    storageBucket: 'app-flutter-facul.firebasestorage.app',
    iosBundleId: 'com.example.trabalhoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPf9XE_oqIrBF5HO1pDxBZyRrwRVLbM5M',
    appId: '1:318699014160:web:00169273f82c079091a295',
    messagingSenderId: '318699014160',
    projectId: 'app-flutter-facul',
    authDomain: 'app-flutter-facul.firebaseapp.com',
    storageBucket: 'app-flutter-facul.firebasestorage.app',
  );
}
